#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LibUniqBuild.Droid.Resource", IsApplication=false)]

namespace LibUniqBuild.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int disappear = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int grow_from_bottom = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int grow_from_bottomleft_to_topright = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int grow_from_bottomright_to_topleft = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int grow_from_top = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int grow_from_topleft_to_bottomright = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int grow_from_topright_to_bottomleft = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int pump_bottom = 2130968583;
			
			// aapt resource value: 0x7f040008
			public static int pump_top = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int shrink_from_bottom = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public static int shrink_from_bottomleft_to_topright = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int shrink_from_bottomright_to_topleft = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public static int shrink_from_top = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public static int shrink_from_topleft_to_bottomright = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public static int shrink_from_topright_to_bottomleft = 2130968590;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public static int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int activity_vertical_margin = 2131034113;
			
			// aapt resource value: 0x7f050004
			public static int float_action_h_padding = 2131034116;
			
			// aapt resource value: 0x7f050003
			public static int float_action_item_gap = 2131034115;
			
			// aapt resource value: 0x7f050002
			public static int float_action_item_padding = 2131034114;
			
			// aapt resource value: 0x7f050006
			public static int float_action_threshold = 2131034118;
			
			// aapt resource value: 0x7f050005
			public static int float_action_v_padding = 2131034117;
			
			// aapt resource value: 0x7f050008
			public static int font_large = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public static int font_large_dp = 2131034124;
			
			// aapt resource value: 0x7f050007
			public static int font_larger = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public static int font_larger_dp = 2131034123;
			
			// aapt resource value: 0x7f050009
			public static int font_normal = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public static int font_normal_dp = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public static int font_small = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public static int font_small_dp = 2131034126;
			
			// aapt resource value: 0x7f050013
			public static int spacing_large = 2131034131;
			
			// aapt resource value: 0x7f050012
			public static int spacing_normal = 2131034130;
			
			// aapt resource value: 0x7f050011
			public static int spacing_small = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public static int spacing_tiny = 2131034127;
			
			// aapt resource value: 0x7f050010
			public static int spacing_tiny8 = 2131034128;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int action_item_btn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int action_item_selected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int arrow_down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int arrow_up = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int popup = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int shadow = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public static int arrow_down = 2131230725;
			
			// aapt resource value: 0x7f080004
			public static int arrow_up = 2131230724;
			
			// aapt resource value: 0x7f080000
			public static int icon = 2131230720;
			
			// aapt resource value: 0x7f080006
			public static int iv_background = 2131230726;
			
			// aapt resource value: 0x7f08000d
			public static int iv_icon = 2131230733;
			
			// aapt resource value: 0x7f080007
			public static int iv_shadow = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public static int layout_left_menu = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public static int layout_right_menu = 2131230732;
			
			// aapt resource value: 0x7f080002
			public static int scroller = 2131230722;
			
			// aapt resource value: 0x7f080009
			public static int sv_left_menu = 2131230729;
			
			// aapt resource value: 0x7f080008
			public static int sv_menu_holder = 2131230728;
			
			// aapt resource value: 0x7f08000b
			public static int sv_right_menu = 2131230731;
			
			// aapt resource value: 0x7f080001
			public static int title = 2131230721;
			
			// aapt resource value: 0x7f080003
			public static int tracks = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public static int tv_title = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int action_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int popup = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int residemenu_custom = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int residemenu_custom_left_scrollview = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int residemenu_custom_right_scrollview = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int residemenu_item = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public static int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public static int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public static int Animations = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int Animations_PopDownMenu = 2131165185;
			
			// aapt resource value: 0x7f070002
			public static int Animations_PopDownMenu_Center = 2131165186;
			
			// aapt resource value: 0x7f070003
			public static int Animations_PopDownMenu_Left = 2131165187;
			
			// aapt resource value: 0x7f070005
			public static int Animations_PopDownMenu_Reflect = 2131165189;
			
			// aapt resource value: 0x7f070004
			public static int Animations_PopDownMenu_Right = 2131165188;
			
			// aapt resource value: 0x7f070006
			public static int Animations_PopUpMenu = 2131165190;
			
			// aapt resource value: 0x7f070007
			public static int Animations_PopUpMenu_Center = 2131165191;
			
			// aapt resource value: 0x7f070008
			public static int Animations_PopUpMenu_Left = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public static int Animations_PopUpMenu_Reflect = 2131165194;
			
			// aapt resource value: 0x7f070009
			public static int Animations_PopUpMenu_Right = 2131165193;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
